name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the app
    - name: Build app
      run: npm run build

    # Test the app (optional, if you have tests)
    #- name: Run tests
    #  run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Deploy to AWS
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /login-service
          git pull origin main
          npm install
          npm run build
          pm2 restart all
